WARNING - sacred_utils - No observers have been added to this run
INFO - sacred_utils - Running command 'main'
INFO - sacred_utils - Started
==============SETTINGS================
{'device': 'cuda:0',
 'env': 'mocca_envs:Walker2DCustomEnv-v0',
 'episode_steps': 40000,
 'experiment_dir': 'runs/2021_02_08__14_39_42__walker_experiment/',
 'gae_lambda': 0.95,
 'gamma': 0.99,
 'log_dir': 'runs/2021_02_08__14_39_42__walker_experiment/logs',
 'log_interval': 2,
 'lr': 0.0003,
 'lr_decay_type': 'exponential',
 'mini_batch_size': 1024,
 'net': None,
 'num_frames': 10000000.0,
 'num_mini_batch': 39,
 'num_processes': 125,
 'num_steps': 320,
 'ppo_params': {'clip_param': 0.2,
                'entropy_coef': 0.0,
                'eps': 1e-05,
                'lr': 0.0003,
                'max_grad_norm': 2.0,
                'num_mini_batch': 39,
                'ppo_epoch': 10,
                'use_clipped_value_loss': False,
                'value_loss_coef': 1.0},
 'replicate_num': 1,
 'save_dir': 'runs/2021_02_08__14_39_42__walker_experiment/models',
 'save_every': 2000000,
 'seed': 16,
 'use_gae': True}
--------------------------------------
/home/yuni/venv/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
pybullet build time: Nov 26 2020 23:09:05
argv[0]=--background_color_red=1.0
argv[1]=--background_color_green=1.0
argv[2]=--background_color_blue=1.0
argv[3]=--width=1280
argv[4]=--height=720
argv[5]=
argv[0]=--background_color_red=1.0
argv[1]=--background_color_green=1.0
argv[2]=--background_color_blue=1.0
argv[3]=--width=1280
argv[4]=--height=720
argv[5]=
Updates 1, num timesteps 40000, FPS 3241, mean/median reward -14.3/-12.5, min/max reward -80.4/21.4, entropy 10.04, value loss 14.95, policy loss -0.022
Updates 2, num timesteps 80000, FPS 3167, mean/median reward -13.1/-10.4, min/max reward -77.1/25.4, entropy 9.86, value loss 13.64, policy loss -0.028
Updates 3, num timesteps 120000, FPS 3015, mean/median reward -10.3/-9.8, min/max reward -64.0/35.3, entropy 9.69, value loss 12.81, policy loss -0.029
Updates 4, num timesteps 160000, FPS 2904, mean/median reward -4.6/-3.3, min/max reward -49.2/35.8, entropy 9.51, value loss 12.37, policy loss -0.030
Updates 5, num timesteps 200000, FPS 2830, mean/median reward -0.0/-2.6, min/max reward -32.3/55.1, entropy 9.34, value loss 11.98, policy loss -0.033
Updates 6, num timesteps 240000, FPS 2798, mean/median reward 4.2/2.7, min/max reward -43.1/47.7, entropy 9.19, value loss 13.32, policy loss -0.031
Updates 7, num timesteps 280000, FPS 2766, mean/median reward 5.1/0.1, min/max reward -42.5/72.7, entropy 9.05, value loss 16.83, policy loss -0.024
Updates 8, num timesteps 320000, FPS 2744, mean/median reward 13.9/13.1, min/max reward -29.1/76.4, entropy 8.93, value loss 20.61, policy loss -0.022
Updates 9, num timesteps 360000, FPS 2718, mean/median reward 16.4/12.7, min/max reward -42.4/105.5, entropy 8.81, value loss 21.78, policy loss -0.023
Updates 10, num timesteps 400000, FPS 2697, mean/median reward 19.5/13.3, min/max reward -47.7/153.5, entropy 8.70, value loss 21.41, policy loss -0.019
Updates 11, num timesteps 440000, FPS 2679, mean/median reward 21.2/14.8, min/max reward -39.4/129.9, entropy 8.59, value loss 21.48, policy loss -0.019
Updates 12, num timesteps 480000, FPS 2662, mean/median reward 25.6/17.9, min/max reward -45.1/181.5, entropy 8.49, value loss 20.77, policy loss -0.020
Updates 13, num timesteps 520000, FPS 2646, mean/median reward 29.8/23.4, min/max reward -44.8/295.3, entropy 8.39, value loss 20.38, policy loss -0.017
Updates 14, num timesteps 560000, FPS 2630, mean/median reward 35.0/29.6, min/max reward -33.4/184.4, entropy 8.29, value loss 24.13, policy loss -0.017
Updates 15, num timesteps 600000, FPS 2623, mean/median reward 30.4/25.9, min/max reward -53.1/104.4, entropy 8.18, value loss 19.77, policy loss -0.016
Updates 16, num timesteps 640000, FPS 2611, mean/median reward 42.7/35.9, min/max reward -32.7/244.5, entropy 8.08, value loss 20.89, policy loss -0.015
Updates 17, num timesteps 680000, FPS 2602, mean/median reward 44.1/29.8, min/max reward -40.4/178.7, entropy 7.97, value loss 20.81, policy loss -0.017
Updates 18, num timesteps 720000, FPS 2595, mean/median reward 45.0/34.9, min/max reward -49.9/217.2, entropy 7.87, value loss 23.97, policy loss -0.016
Updates 19, num timesteps 760000, FPS 2589, mean/median reward 48.9/43.4, min/max reward -42.5/161.0, entropy 7.77, value loss 23.51, policy loss -0.015
Updates 20, num timesteps 800000, FPS 2584, mean/median reward 63.5/46.5, min/max reward -29.2/270.2, entropy 7.68, value loss 24.46, policy loss -0.020
Updates 21, num timesteps 840000, FPS 2582, mean/median reward 66.8/49.7, min/max reward -27.5/267.4, entropy 7.60, value loss 25.48, policy loss -0.017
Updates 22, num timesteps 880000, FPS 2579, mean/median reward 67.5/45.7, min/max reward -49.5/434.0, entropy 7.51, value loss 21.66, policy loss -0.018
Updates 23, num timesteps 920000, FPS 2577, mean/median reward 92.1/55.8, min/max reward -39.2/743.1, entropy 7.42, value loss 21.94, policy loss -0.016
Updates 24, num timesteps 960000, FPS 2574, mean/median reward 94.7/76.6, min/max reward -63.0/423.1, entropy 7.35, value loss 29.07, policy loss -0.016
Updates 25, num timesteps 1000000, FPS 2576, mean/median reward 108.1/81.0, min/max reward -34.0/669.2, entropy 7.29, value loss 30.12, policy loss -0.020
Updates 26, num timesteps 1040000, FPS 2572, mean/median reward 128.6/84.4, min/max reward -43.6/728.6, entropy 7.20, value loss 27.54, policy loss -0.017
Updates 27, num timesteps 1080000, FPS 2567, mean/median reward 158.2/110.4, min/max reward -46.5/765.5, entropy 7.12, value loss 25.73, policy loss -0.016
Updates 28, num timesteps 1120000, FPS 2567, mean/median reward 242.5/149.5, min/max reward -67.9/1186.0, entropy 7.05, value loss 25.33, policy loss -0.018
Updates 29, num timesteps 1160000, FPS 2563, mean/median reward 283.6/134.5, min/max reward -67.9/1471.1, entropy 6.98, value loss 18.89, policy loss -0.014
Updates 30, num timesteps 1200000, FPS 2558, mean/median reward 535.1/315.6, min/max reward -62.0/1488.6, entropy 6.89, value loss 18.04, policy loss -0.015
Updates 31, num timesteps 1240000, FPS 2558, mean/median reward 654.0/372.6, min/max reward -33.0/1516.4, entropy 6.83, value loss 14.97, policy loss -0.013
Updates 32, num timesteps 1280000, FPS 2562, mean/median reward 762.2/701.7, min/max reward -13.4/1535.6, entropy 6.76, value loss 11.24, policy loss -0.011
Updates 33, num timesteps 1320000, FPS 2564, mean/median reward 908.8/1407.5, min/max reward -41.1/1543.5, entropy 6.68, value loss 9.03, policy loss -0.007
Updates 34, num timesteps 1360000, FPS 2566, mean/median reward 1024.0/1429.2, min/max reward -41.1/1566.5, entropy 6.56, value loss 6.94, policy loss -0.011
Updates 35, num timesteps 1400000, FPS 2564, mean/median reward 1149.4/1457.0, min/max reward -4.3/1567.2, entropy 6.46, value loss 4.02, policy loss -0.002
Updates 36, num timesteps 1440000, FPS 2564, mean/median reward 1209.8/1468.9, min/max reward 4.8/1582.6, entropy 6.36, value loss 4.35, policy loss -0.008
Updates 37, num timesteps 1480000, FPS 2564, mean/median reward 1319.0/1487.8, min/max reward 4.8/1626.1, entropy 6.25, value loss 3.47, policy loss -0.007
Updates 38, num timesteps 1520000, FPS 2567, mean/median reward 1301.5/1497.4, min/max reward 4.8/1626.1, entropy 6.14, value loss 3.55, policy loss -0.007
Updates 39, num timesteps 1560000, FPS 2570, mean/median reward 1254.3/1508.1, min/max reward -9.6/1626.1, entropy 6.05, value loss 4.64, policy loss -0.011
Updates 40, num timesteps 1600000, FPS 2570, mean/median reward 1201.2/1517.6, min/max reward -9.6/1598.5, entropy 5.98, value loss 3.97, policy loss -0.012
Updates 41, num timesteps 1640000, FPS 2568, mean/median reward 1228.1/1525.6, min/max reward -3.2/1616.2, entropy 5.89, value loss 4.53, policy loss 0.001
Updates 42, num timesteps 1680000, FPS 2567, mean/median reward 1162.4/1531.8, min/max reward -53.2/1616.2, entropy 5.82, value loss 11.39, policy loss -0.013
Updates 43, num timesteps 1720000, FPS 2566, mean/median reward 953.5/1529.6, min/max reward -53.2/1647.6, entropy 5.78, value loss 16.23, policy loss -0.014
Updates 44, num timesteps 1760000, FPS 2566, mean/median reward 1094.7/1542.7, min/max reward -34.2/1647.6, entropy 5.71, value loss 3.84, policy loss -0.009
Updates 45, num timesteps 1800000, FPS 2565, mean/median reward 1150.5/1547.3, min/max reward -34.2/1647.6, entropy 5.63, value loss 3.79, policy loss -0.005
Updates 46, num timesteps 1840000, FPS 2565, mean/median reward 1351.3/1550.8, min/max reward -23.3/1632.7, entropy 5.54, value loss 3.64, policy loss -0.010
Updates 47, num timesteps 1880000, FPS 2566, mean/median reward 1302.2/1547.1, min/max reward -23.3/1629.1, entropy 5.48, value loss 9.82, policy loss 0.021
Updates 48, num timesteps 1920000, FPS 2569, mean/median reward 998.5/1346.0, min/max reward -24.1/1619.2, entropy 5.45, value loss 13.37, policy loss 0.001
Updates 49, num timesteps 1960000, FPS 2571, mean/median reward 889.0/1059.2, min/max reward -24.1/1602.2, entropy 5.44, value loss 10.79, policy loss -0.010
Updates 50, num timesteps 2000000, FPS 2573, mean/median reward 1049.8/1549.9, min/max reward -28.9/1634.7, entropy 5.41, value loss 11.77, policy loss -0.013
Updates 51, num timesteps 2040000, FPS 2575, mean/median reward 1103.2/1550.4, min/max reward -28.9/1634.7, entropy 5.36, value loss 5.49, policy loss -0.012
Updates 52, num timesteps 2080000, FPS 2576, mean/median reward 1150.4/1552.5, min/max reward -28.9/1615.7, entropy 5.28, value loss 3.45, policy loss -0.009
Updates 53, num timesteps 2120000, FPS 2576, mean/median reward 1353.9/1564.8, min/max reward -38.9/1616.6, entropy 5.18, value loss 3.22, policy loss -0.004
Updates 54, num timesteps 2160000, FPS 2576, mean/median reward 1385.6/1573.8, min/max reward -38.9/1626.3, entropy 5.10, value loss 5.36, policy loss -0.008
Updates 55, num timesteps 2200000, FPS 2578, mean/median reward 1327.2/1580.7, min/max reward -56.1/1658.3, entropy 5.03, value loss 3.91, policy loss 0.020
Updates 56, num timesteps 2240000, FPS 2580, mean/median reward 1368.2/1593.2, min/max reward -56.1/1658.3, entropy 4.95, value loss 2.13, policy loss -0.007
Updates 57, num timesteps 2280000, FPS 2582, mean/median reward 1385.1/1603.4, min/max reward -56.1/1658.3, entropy 4.85, value loss 2.52, policy loss -0.006
Updates 58, num timesteps 2320000, FPS 2584, mean/median reward 1427.0/1608.5, min/max reward 18.9/1641.6, entropy 4.72, value loss 1.92, policy loss -0.004
Updates 59, num timesteps 2360000, FPS 2583, mean/median reward 1463.2/1620.4, min/max reward 6.2/1663.6, entropy 4.60, value loss 2.42, policy loss -0.008
Updates 60, num timesteps 2400000, FPS 2581, mean/median reward 1493.1/1626.2, min/max reward 4.2/1663.6, entropy 4.49, value loss 3.48, policy loss -0.006
Updates 61, num timesteps 2440000, FPS 2580, mean/median reward 1510.6/1631.6, min/max reward 4.2/1698.3, entropy 4.38, value loss 1.00, policy loss -0.004
Updates 62, num timesteps 2480000, FPS 2577, mean/median reward 1554.2/1639.1, min/max reward 4.2/1698.3, entropy 4.31, value loss 1.47, policy loss -0.003
Updates 63, num timesteps 2520000, FPS 2577, mean/median reward 1548.6/1645.8, min/max reward 21.5/1698.3, entropy 4.23, value loss 1.18, policy loss 0.005
Updates 64, num timesteps 2560000, FPS 2575, mean/median reward 1565.1/1652.8, min/max reward 21.5/1697.5, entropy 4.16, value loss 0.88, policy loss -0.002
Updates 65, num timesteps 2600000, FPS 2573, mean/median reward 1537.6/1660.6, min/max reward 21.5/1683.6, entropy 4.09, value loss 2.10, policy loss -0.005
Updates 66, num timesteps 2640000, FPS 2571, mean/median reward 1555.8/1664.7, min/max reward 18.7/1685.1, entropy 4.02, value loss 2.30, policy loss 0.003
Updates 67, num timesteps 2680000, FPS 2569, mean/median reward 1565.5/1665.3, min/max reward 16.9/1685.1, entropy 3.94, value loss 1.21, policy loss -0.006
Updates 68, num timesteps 2720000, FPS 2568, mean/median reward 1553.5/1668.3, min/max reward 13.8/1692.0, entropy 3.88, value loss 4.26, policy loss -0.004
Updates 69, num timesteps 2760000, FPS 2567, mean/median reward 1530.8/1673.9, min/max reward 6.0/1695.4, entropy 3.83, value loss 2.95, policy loss -0.005
Updates 70, num timesteps 2800000, FPS 2568, mean/median reward 1482.8/1677.3, min/max reward 6.0/1710.9, entropy 3.77, value loss 4.36, policy loss -0.006
Updates 71, num timesteps 2840000, FPS 2569, mean/median reward 1499.3/1681.7, min/max reward 6.0/1710.9, entropy 3.72, value loss 5.08, policy loss -0.005
Updates 72, num timesteps 2880000, FPS 2570, mean/median reward 1526.3/1685.1, min/max reward 9.8/1722.5, entropy 3.68, value loss 6.04, policy loss -0.007
Updates 73, num timesteps 2920000, FPS 2571, mean/median reward 1541.2/1686.6, min/max reward 9.8/1722.5, entropy 3.61, value loss 2.51, policy loss -0.005
Updates 74, num timesteps 2960000, FPS 2572, mean/median reward 1573.8/1693.8, min/max reward 10.5/1722.5, entropy 3.54, value loss 2.84, policy loss -0.002
Updates 75, num timesteps 3000000, FPS 2572, mean/median reward 1593.5/1696.1, min/max reward 17.3/1715.9, entropy 3.48, value loss 2.47, policy loss -0.003
Updates 76, num timesteps 3040000, FPS 2571, mean/median reward 1597.6/1698.9, min/max reward 17.3/1720.2, entropy 3.38, value loss 0.47, policy loss 0.005
Updates 77, num timesteps 3080000, FPS 2570, mean/median reward 1601.0/1703.2, min/max reward 19.3/1728.5, entropy 3.30, value loss 0.55, policy loss -0.011
Updates 78, num timesteps 3120000, FPS 2571, mean/median reward 1633.7/1708.9, min/max reward 94.7/1736.4, entropy 3.21, value loss 1.13, policy loss 0.007
Updates 79, num timesteps 3160000, FPS 2571, mean/median reward 1623.5/1713.6, min/max reward 30.2/1758.2, entropy 3.14, value loss 3.67, policy loss -0.007
Updates 80, num timesteps 3200000, FPS 2573, mean/median reward 1640.7/1719.3, min/max reward 30.2/1758.2, entropy 3.07, value loss 0.33, policy loss 0.032
Updates 81, num timesteps 3240000, FPS 2574, mean/median reward 1357.0/1723.8, min/max reward -41.2/1760.8, entropy 3.03, value loss 23.21, policy loss -0.006
Updates 82, num timesteps 3280000, FPS 2576, mean/median reward 1017.9/1725.1, min/max reward -41.2/1760.8, entropy 3.03, value loss 15.87, policy loss -0.012
Updates 83, num timesteps 3320000, FPS 2577, mean/median reward 1150.0/1730.4, min/max reward -49.1/1753.0, entropy 3.02, value loss 5.60, policy loss -0.008
Updates 84, num timesteps 3360000, FPS 2578, mean/median reward 1377.5/1734.2, min/max reward -49.1/1756.8, entropy 2.97, value loss 1.83, policy loss -0.001
Updates 85, num timesteps 3400000, FPS 2581, mean/median reward 1520.2/1736.2, min/max reward -49.1/1756.8, entropy 2.93, value loss 6.79, policy loss -0.007
Updates 86, num timesteps 3440000, FPS 2583, mean/median reward 1544.4/1738.3, min/max reward -3.6/1761.5, entropy 2.90, value loss 4.57, policy loss -0.010
Updates 87, num timesteps 3480000, FPS 2584, mean/median reward 1533.1/1740.0, min/max reward -3.6/1761.5, entropy 2.85, value loss 5.44, policy loss -0.001
Updates 88, num timesteps 3520000, FPS 2586, mean/median reward 1660.8/1743.3, min/max reward 8.7/1772.5, entropy 2.79, value loss 2.04, policy loss 0.001
Updates 89, num timesteps 3560000, FPS 2588, mean/median reward 1651.0/1743.8, min/max reward 8.7/1773.7, entropy 2.74, value loss 1.36, policy loss 0.014
Updates 90, num timesteps 3600000, FPS 2590, mean/median reward 1642.6/1750.3, min/max reward 11.6/1773.7, entropy 2.71, value loss 7.62, policy loss -0.009
Updates 91, num timesteps 3640000, FPS 2590, mean/median reward 1469.4/1754.4, min/max reward -0.5/1773.7, entropy 2.69, value loss 10.83, policy loss -0.008
Updates 92, num timesteps 3680000, FPS 2590, mean/median reward 1471.6/1756.6, min/max reward -0.5/1773.8, entropy 2.66, value loss 4.22, policy loss -0.005
Updates 93, num timesteps 3720000, FPS 2590, mean/median reward 1542.6/1757.1, min/max reward -0.5/1776.8, entropy 2.61, value loss 2.11, policy loss -0.002
Updates 94, num timesteps 3760000, FPS 2592, mean/median reward 1568.2/1756.5, min/max reward -3.5/1782.4, entropy 2.57, value loss 5.94, policy loss -0.007
Updates 95, num timesteps 3800000, FPS 2592, mean/median reward 1582.4/1756.7, min/max reward -3.5/1782.4, entropy 2.52, value loss 1.59, policy loss 0.000
Updates 96, num timesteps 3840000, FPS 2594, mean/median reward 1610.7/1759.1, min/max reward -3.5/1785.8, entropy 2.45, value loss 0.90, policy loss -0.001
Updates 97, num timesteps 3880000, FPS 2595, mean/median reward 1708.1/1761.9, min/max reward 23.9/1785.8, entropy 2.38, value loss 0.92, policy loss -0.003
Updates 98, num timesteps 3920000, FPS 2595, mean/median reward 1694.3/1762.4, min/max reward 16.6/1785.8, entropy 2.31, value loss 1.47, policy loss -0.006
Updates 99, num timesteps 3960000, FPS 2597, mean/median reward 1671.0/1765.4, min/max reward 2.3/1788.1, entropy 2.24, value loss 1.96, policy loss -0.009
Updates 100, num timesteps 4000000, FPS 2598, mean/median reward 1646.9/1768.4, min/max reward 2.3/1791.7, entropy 2.18, value loss 2.68, policy loss -0.007
Updates 101, num timesteps 4040000, FPS 2599, mean/median reward 1624.7/1772.3, min/max reward 9.4/1796.5, entropy 2.13, value loss 3.82, policy loss -0.009
Updates 102, num timesteps 4080000, FPS 2600, mean/median reward 1642.4/1773.4, min/max reward 9.4/1796.5, entropy 2.08, value loss 0.81, policy loss -0.002
Updates 103, num timesteps 4120000, FPS 2601, mean/median reward 1660.2/1774.6, min/max reward 9.4/1796.5, entropy 2.01, value loss 0.87, policy loss 0.003
Updates 104, num timesteps 4160000, FPS 2602, mean/median reward 1690.7/1777.9, min/max reward 18.5/1796.9, entropy 1.97, value loss 1.78, policy loss -0.006
Updates 105, num timesteps 4200000, FPS 2602, mean/median reward 1661.6/1780.7, min/max reward 14.1/1796.9, entropy 1.92, value loss 2.00, policy loss -0.000
Updates 106, num timesteps 4240000, FPS 2602, mean/median reward 1611.7/1781.7, min/max reward 14.1/1825.4, entropy 1.89, value loss 1.94, policy loss -0.007
Updates 107, num timesteps 4280000, FPS 2602, mean/median reward 1587.5/1784.9, min/max reward 14.1/1844.7, entropy 1.86, value loss 2.31, policy loss -0.010
Updates 108, num timesteps 4320000, FPS 2605, mean/median reward 1571.4/1785.7, min/max reward -0.9/1844.7, entropy 1.82, value loss 3.86, policy loss -0.012
Updates 109, num timesteps 4360000, FPS 2606, mean/median reward 1584.7/1787.4, min/max reward -0.9/1844.7, entropy 1.78, value loss 2.73, policy loss -0.007
Updates 110, num timesteps 4400000, FPS 2607, mean/median reward 1626.9/1790.1, min/max reward -0.9/1834.7, entropy 1.73, value loss 1.31, policy loss -0.002
Updates 111, num timesteps 4440000, FPS 2608, mean/median reward 1670.7/1791.7, min/max reward 3.7/1834.7, entropy 1.65, value loss 0.59, policy loss 0.003
Updates 112, num timesteps 4480000, FPS 2609, mean/median reward 1736.9/1791.5, min/max reward 59.0/1834.7, entropy 1.60, value loss 1.36, policy loss 0.036
Updates 113, num timesteps 4520000, FPS 2609, mean/median reward 907.8/871.8, min/max reward -13.8/1797.1, entropy 1.59, value loss 33.45, policy loss -0.012
Updates 114, num timesteps 4560000, FPS 2610, mean/median reward 402.5/302.6, min/max reward 8.3/1790.9, entropy 1.58, value loss 31.45, policy loss -0.019
Updates 115, num timesteps 4600000, FPS 2610, mean/median reward 465.8/379.2, min/max reward -3.9/1778.7, entropy 1.57, value loss 15.17, policy loss -0.017
Updates 116, num timesteps 4640000, FPS 2609, mean/median reward 712.0/544.2, min/max reward -3.9/1765.8, entropy 1.54, value loss 3.49, policy loss -0.015
Updates 117, num timesteps 4680000, FPS 2609, mean/median reward 1276.2/1698.4, min/max reward -3.9/1840.4, entropy 1.49, value loss 4.21, policy loss -0.008
Updates 118, num timesteps 4720000, FPS 2609, mean/median reward 1629.6/1723.9, min/max reward 1.4/1842.6, entropy 1.43, value loss 0.50, policy loss 0.000
Updates 119, num timesteps 4760000, FPS 2609, mean/median reward 1667.3/1725.9, min/max reward 1.4/1842.6, entropy 1.38, value loss 0.65, policy loss -0.004
Updates 120, num timesteps 4800000, FPS 2609, mean/median reward 1693.5/1768.0, min/max reward 36.9/1859.6, entropy 1.33, value loss 1.14, policy loss -0.006
Updates 121, num timesteps 4840000, FPS 2609, mean/median reward 1724.9/1782.6, min/max reward 36.9/1859.6, entropy 1.27, value loss 0.22, policy loss 0.009
Updates 122, num timesteps 4880000, FPS 2609, mean/median reward 1748.6/1789.2, min/max reward 36.9/1859.6, entropy 1.22, value loss 0.17, policy loss -0.004
Updates 123, num timesteps 4920000, FPS 2610, mean/median reward 1741.5/1792.5, min/max reward 51.3/1865.1, entropy 1.17, value loss 0.88, policy loss -0.009
Updates 124, num timesteps 4960000, FPS 2611, mean/median reward 1744.2/1795.3, min/max reward 51.3/1865.1, entropy 1.12, value loss 0.21, policy loss 0.002
Updates 125, num timesteps 5000000, FPS 2611, mean/median reward 1745.0/1795.6, min/max reward 51.3/1865.1, entropy 1.05, value loss 0.11, policy loss -0.011
Updates 126, num timesteps 5040000, FPS 2611, mean/median reward 1758.4/1797.6, min/max reward 51.3/1856.4, entropy 0.99, value loss 0.37, policy loss -0.010
Updates 127, num timesteps 5080000, FPS 2610, mean/median reward 1732.4/1799.3, min/max reward 60.9/1858.4, entropy 0.96, value loss 0.64, policy loss -0.004
Updates 128, num timesteps 5120000, FPS 2610, mean/median reward 1719.9/1800.0, min/max reward 60.9/1858.4, entropy 0.92, value loss 0.25, policy loss 0.000
Process ForkProcess-125:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-124:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-123:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-122:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-121:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-120:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-119:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-118:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-117:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-116:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-115:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-114:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-113:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-112:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-111:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-110:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-109:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-108:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-107:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-106:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-105:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-104:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-103:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-102:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-101:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-100:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-99:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-98:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-97:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-96:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-95:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-94:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-93:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-92:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-91:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-90:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-89:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-88:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-87:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-86:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-85:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-84:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-83:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-82:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-81:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-80:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-79:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-78:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-77:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-76:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-75:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-74:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-73:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-72:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-71:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-70:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-69:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-68:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-67:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-66:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-65:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-64:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-63:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-62:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-61:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-60:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-59:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-58:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-57:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-56:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-55:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-54:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-53:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-52:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-51:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-50:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-49:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-48:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-47:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-46:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-45:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-44:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-43:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-42:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-41:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-40:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-39:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-38:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-37:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-36:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-35:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-34:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-33:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-32:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-31:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-30:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-29:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-28:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-27:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-26:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-25:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-24:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-23:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-22:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-20:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-18:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-16:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-14:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-13:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process ForkProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuni/SteppingStone/common/envs_utils.py", line 646, in _subproc_worker
    cmd, data = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
